//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailOrder
    {
        public int DetailID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Price { get; set; }
        public string Status { get; set; }
    
        public virtual HeaderOrder HeaderOrder { get; set; }
        public virtual MsMenu MsMenu { get; set; }
    }
}
