//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderOrder()
        {
            this.DetailOrders = new HashSet<DetailOrder>();
        }
    
        public string OrderID { get; set; }
        public string EmployeeID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Payment { get; set; }
        public string Bank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailOrder> DetailOrders { get; set; }
        public virtual MsEmployee MsEmployee { get; set; }
        public virtual MsMember MsMember { get; set; }
    }
}
