//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranLKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranLKSEntities : DbContext
    {
        public RestoranLKSEntities()
            : base("name=RestoranLKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetailOrder> DetailOrders { get; set; }
        public virtual DbSet<HeaderOrder> HeaderOrders { get; set; }
        public virtual DbSet<MsEmployee> MsEmployees { get; set; }
        public virtual DbSet<MsMember> MsMembers { get; set; }
        public virtual DbSet<MsMenu> MsMenus { get; set; }
    }
}
