//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsMember()
        {
            this.HeaderOrders = new HashSet<HeaderOrder>();
        }
    
        public string MemberID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Handphone { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderOrder> HeaderOrders { get; set; }
    }
}
